const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { ensureDirectoryExists } = require('./FileUtils');

/**
 * Checks if a file is a test file based on its path.
 * @param {string} filePath - The file path to check.
 * @returns {boolean} - True if it's a test file; otherwise, false.
 */
function isTestFile(filePath) {
    return filePath.includes('/test/');
}

/**
 * Shows the diff between two files.
 * @param {string} originalPath - The path to the original file.
 * @param {string} newPath - The path to the new file.
 * @param {string} fileLabel - The label for the file being diffed.
 */
function showDiff(originalPath, newPath, fileLabel) {
    console.log(`\n--- Proposed changes for ${fileLabel}: ${originalPath} ---`);
    try {
        const diffOutput = execSync(`diff --label "Original" ${originalPath} --label "Proposed" ${newPath}`).toString();
        console.log(diffOutput);
    } catch (diffError) {
        if (diffError.stdout) {
            console.log(diffError.stdout.toString());
        } else {
            console.error(`Error diffing files: ${diffError.message}`);
        }
    }
    console.log(`--- End of proposed changes for ${fileLabel}: ${originalPath} ---\n`);
}

/**
 * Parses and applies generated code from the AI client.
 * @param {string} generatedCode - The code generated by the AI client.
 * @param {string} tmpDir - The temporary directory for intermediate files.
 */
function parseAndApplyGeneratedCode(rootDir, tmpDir, generatedCode) {
    console.log(`Parsing and applying generated code from ${rootDir}`);
    const codeBlocks = generatedCode.split(/File: (.+?)\n/).slice(1);

    for (let i = 0; i < codeBlocks.length; i += 2) {
        const filePath = codeBlocks[i].trim();
        const fileContent = codeBlocks[i + 1].trim();
        const fullPath = path.resolve(rootDir, filePath);
        const tempFilePath = path.resolve(tmpDir, filePath);

        // ensure the temp file directory exists
        ensureDirectoryExists(path.dirname(tempFilePath));

        // write the file content to the temp file
        fs.writeFileSync(tempFilePath, fileContent);

        // Ensure the directory exists
        const dirName = path.dirname(fullPath);
        ensureDirectoryExists(dirName);

        const isTestFileFlag = isTestFile(filePath);

        if (isTestFileFlag) {
            console.warn(`WARNING: Attempted to modify a test file: ${filePath}. Changes will not be applied.`);
            showDiff(fullPath, tempFilePath, 'test file');
            continue; // Skip applying changes to test files
        }

        // Check if the file is new or a non-Java file
        const isNewFile = !fs.existsSync(fullPath);
        const isJavaFile = filePath.endsWith('.java');

        if (isNewFile) {
            console.log(`New file will be added: ${filePath}`);
            console.log(`Contents of the new file:\n${fileContent}`);
        } else if (!isJavaFile) {
            console.log(`WARNING: A non-Java file will be changed: ${filePath}`);
            showDiff(fullPath, tempFilePath, 'non-Java file');
        } else {
            // Archive the original file
            const timestamp = new Date().toISOString().replace(/[-:.]/g, '');
            const archiveDir = path.join(tmpDir, 'archive/versions', path.dirname(filePath));
            ensureDirectoryExists(archiveDir);
            const archivePath = path.join(archiveDir, `${path.basename(filePath, '.java')}_${timestamp}.java`);
            fs.copyFileSync(fullPath, archivePath);

            // Show diff for existing files
            showDiff(fullPath, tempFilePath, 'file');
        }

        // Write the file content
        fs.writeFileSync(fullPath, fileContent);

        // delete the temp file
        fs.unlinkSync(tempFilePath);
    }
}

module.exports = { parseAndApplyGeneratedCode }; 