const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { ensureDirectoryExists } = require('./FileUtils');
const logger = require('./logger');

/**
 * Checks if a file is a test file based on its path.
 * @param {string} filePath - The file path to check.
 * @returns {boolean} - True if it's a test file; otherwise, false.
 */
function isTestFile(filePath) {
    return filePath.includes('/test/');
}

/**
 * Shows the diff between two files.
 * @param {string} originalPath - The path to the original file.
 * @param {string} newPath - The path to the new file.
 * @param {string} fileLabel - The label for the file being diffed.
 * @returns {boolean} - True if the diff is meaningful; otherwise, false.
 */
function showDiff(originalPath, newPath, fileLabel) {
    try {
        const diffOutput = execSync(`diff --label "Original" ${originalPath} --label "Proposed" ${newPath}`).toString();
        
        // Check if the diff output contains meaningful changes
        const meaningfulDiff = diffOutput.split('\n').some(line => line.trim() && !line.startsWith('---') && !line.startsWith('+++'));
        
        if (meaningfulDiff) {
            logger.info(`Proposed changes for ${fileLabel}: ${originalPath}`);
            logger.info(diffOutput);
            return true;
        } else {
            logger.info(`No meaningful changes detected for ${fileLabel}: ${originalPath}`);
            return false;
        }
    } catch (diffError) {
        if (diffError.stdout) {
            const diffOutput = diffError.stdout.toString();
            const meaningfulDiff = diffOutput.split('\n').some(line => line.trim() && !line.startsWith('---') && !line.startsWith('+++'));
            
            if (meaningfulDiff) {
                logger.info(diffOutput);
                return true;
            } else {
                logger.info(`No meaningful changes detected for ${fileLabel}: ${originalPath}`);
                return false;
            }
        } else {
            logger.error(`Error diffing files: ${diffError.message}`);
            return false;
        }
    }
}

/**
 * Parses and applies generated code from the AI client.
 * @param {string} generatedCode - The code generated by the AI client.
 * @param {string} tmpDir - The temporary directory for intermediate files.
 */
function parseAndApplyGeneratedCode(rootDir, tmpDir, generatedCode) {
    logger.debug(`Parsing and applying generated code from ${rootDir}`);
    const codeBlocks = generatedCode.split(/File: (.+?)\n/).slice(1);

    logger.debug(`Found ${codeBlocks.length} code blocks in the generated code.`);

    if (codeBlocks.length === 0) {
        logger.error('No code blocks found in the generated code.');
        return;
    }

    let filesChanged = 0;
    let filesAdded = 0;
    let nonSourceFilesChanged = 0;
    let noMeaningfulDiffCount = 0;

    for (let i = 0; i < codeBlocks.length; i += 2) {
        const filePath = codeBlocks[i].trim();
        const fileContent = codeBlocks[i + 1].trim();
        const fullPath = path.join(rootDir, filePath);
        const tempFilePath = path.join(tmpDir, filePath);

        const cleanedFileContent = fileContent.replace(/```[^\n]*```/g, '').trim();

        logger.debug(`Processing code block ${i + 1} of ${codeBlocks.length}: ${filePath}`);

        ensureDirectoryExists(path.dirname(tempFilePath));

        if (cleanedFileContent.length === 0 || cleanedFileContent.trim() === '') {
            logger.error(`File content is empty for file: ${filePath}`);
            continue;
        }

        fs.writeFileSync(tempFilePath, cleanedFileContent);

        const dirName = path.dirname(fullPath);
        ensureDirectoryExists(dirName);

        const isTestFileFlag = isTestFile(filePath);

        if (isTestFileFlag) {
            logger.warn(`Attempted to modify a test file: ${filePath}. Changes will not be applied.`);
            if (!showDiff(fullPath, tempFilePath, 'test file')) {
                noMeaningfulDiffCount++;
            }
            continue;
        }

        const isNewFile = !fs.existsSync(fullPath);
        const isSrcFile = filePath.endsWith(this.extension);

        if (isNewFile) {
            logger.debug(`New file will be added: ${filePath}`);
            logger.debug(`Contents of the new file:\n${cleanedFileContent}`);
            filesAdded++;
        } else if (!isSrcFile) {
            logger.warn(`A non-source file will be changed: ${filePath}`);
            if (showDiff(fullPath, tempFilePath, 'non-source file')) {
                nonSourceFilesChanged++;
            } else {
                noMeaningfulDiffCount++;
            }
        } else {
            const timestamp = new Date().toISOString().replace(/[-:.]/g, '');
            const archiveDir = path.join(tmpDir, 'archive/versions', path.dirname(filePath));
            ensureDirectoryExists(archiveDir);
            const archivePath = path.join(archiveDir, `${path.basename(filePath, '.java')}_${timestamp}.java`);
            fs.copyFileSync(fullPath, archivePath);

            if (showDiff(fullPath, tempFilePath, 'file')) {
                filesChanged++;
            } else {
                noMeaningfulDiffCount++;
            }
        }

        fs.writeFileSync(fullPath, cleanedFileContent);
        fs.unlinkSync(tempFilePath);
    }

    logger.debug(`Summary: ${filesChanged} source files changed, ${filesAdded} files added, ${nonSourceFilesChanged} non-source files changed, ${noMeaningfulDiffCount} files had no meaningful diff.`);
    console.log(`Summary: ${filesChanged} source files changed, ${filesAdded} files added, ${nonSourceFilesChanged} non-source files changed, ${noMeaningfulDiffCount} files had no meaningful diff.`);
}

module.exports = { parseAndApplyGeneratedCode }; 